import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.20")

    id("com.github.johnrengelman.shadow").version("4.0.4")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // App dependencies
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.3.20")
    implementation("io.javalin:javalin:2.6.0")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.9.8")

    // For config
    implementation("com.uchuhimo:konf:0.13.1")
    implementation("commons-codec:commons-codec:1.12")
    implementation("org.yaml:snakeyaml:1.21")

    // DI
    implementation("org.koin:koin-core:1.0.2")

    // DB Stuff
    implementation("org.postgresql:postgresql:42.2.5")
    implementation("com.zaxxer:HikariCP:3.3.0")
    implementation("org.jdbi:jdbi3-core:3.6.0")
    implementation("org.jdbi:jdbi3-sqlobject:3.6.0")
    implementation("org.jdbi:jdbi3-jodatime2:3.6.0")
    implementation("org.jdbi:jdbi3-kotlin:3.6.0")
    implementation("org.jdbi:jdbi3-kotlin-sqlobject:3.6.0")
    implementation("org.jdbi:jdbi3-postgres:3.6.0")
}

application {
    // Define the main class for the application.
    mainClassName = "de.rockyj.AppKt"
    applicationDefaultJvmArgs = listOf(
            "-Dapplication.environment=${System.getProperty("application.environment")}",
            "-Dapplication.key=${System.getProperty("application.key")}",
            "-Dapplication.iv=${System.getProperty("application.iv")}")
}
